![New York City schoolbus](schoolbus.jpg)

Photo by [Jannis Lucas](https://unsplash.com/@jannis_lucas) on [Unsplash](https://unsplash.com).
<br>

Every year, American high school students take SATs, which are standardized tests intended to measure literacy, numeracy, and writing skills. There are three sections - reading, math, and writing, each with a **maximum score of 800 points**. These tests are extremely important for students and colleges, as they play a pivotal role in the admissions process.

Analyzing the performance of schools is important for a variety of stakeholders, including policy and education professionals, researchers, government, and even parents considering which school their children should attend. 

You have been provided with a dataset called `schools.csv`, which is previewed below.

You have been tasked with answering three key questions about New York City (NYC) public school SAT performance.

In [138]:
# Re-run this cell 
import pandas as pd

# Read in the data
schools = pd.read_csv("schools.csv")

# Preview the data
schools.head()
# print(schools.columns)

best_math_schools = schools[schools["average_math"]>=640][["school_name","average_math"]].sort_values("average_math", ascending=False)

schools["total_SAT"] = schools[["average_math", "average_reading", "average_writing"]].sum(axis=1)
# print(schools[["average_math", "average_reading", "average_writing", "total_SAT"]].head())
top_10_schools = schools[["school_name","total_SAT"]].sort_values("total_SAT", ascending=False).head(10)

a = pd.DataFrame()
a["num_schools"] = schools.groupby("borough").agg("size").round(decimals = 2)
a["average_SAT"] = schools.groupby("borough")["total_SAT"].mean().round(decimals = 2)
a["std_SAT"] = schools.groupby("borough")["total_SAT"].std().round(decimals = 2)
largest_std_dev = a.sort_values("std_SAT", ascending=False).head(1)
print(largest_std_dev)

           num_schools  average_SAT  std_SAT
borough
Manhattan           89      1340.13   230.29