The Nobel Prize has been among the most prestigious international awards since 1901. Each year, awards are bestowed in chemistry, literature, physics, physiology or medicine, economics, and peace. In addition to the honor, prestige, and substantial prize money, the recipient also gets a gold medal with an image of Alfred Nobel (1833 - 1896), who established the prize.

![](Nobel_Prize.png)

The Nobel Foundation has made a dataset available of all prize winners from the outset of the awards from 1901 to 2023. The dataset used in this project is from the Nobel Prize API and is available in the `nobel.csv` file in the `data` folder.

In this project, you'll get a chance to explore and answer several questions related to this prizewinning data. And we encourage you then to explore further questions that you're interested in!

In [67]:
# Loading in required libraries
import pandas as pd
import seaborn as sns
import numpy as np

# Start coding here!
nobel_df = pd.read_csv('data/nobel.csv')
pd.options.display.max_columns = 100
print(nobel_df['sex'].value_counts())
top_gender = 'Male'
print(nobel_df['birth_country'].value_counts())
top_country = 'United States of America'

nobel_df['decade'] = (nobel_df['year']/10).astype(int) * 10
nobel_df_us = nobel_df[['decade', 'birth_country']]
print(nobel_df_us.groupby('decade').apply(lambda s: s.birth_country.value_counts()['United States of America'] / s.birth_country.value_counts().sum()))
max_decade_usa = 2000 

nobel_df_f = nobel_df[['decade', 'category', 'sex']]
print(nobel_df_f.groupby(['decade', 'category']).apply(lambda s: (s.sex == 'Female').sum() / s.sex.value_counts().sum()).sort_values(ascending=False))
max_female_dict = {2020:'Peace', 2020:'Literature', 2010:'Peace'}

nobel_df_ff = nobel_df[['year', 'category', 'full_name', 'sex']]
nobel_df_ff = nobel_df_ff[nobel_df_ff['sex'] == 'Female']
print(nobel_df_ff.sort_values(by='year'))
first_woman_name = 'Marie Curie, née Sklodowska'
first_woman_category = 'Physics'

repeat_list = nobel_df[nobel_df.duplicated(subset=['full_name'], keep=False)]['full_name'].unique().tolist()

Male      905
Female     65
Name: sex, dtype: int64
United States of America                        291
United Kingdom                                   91
Germany                                          67
France                                           58
Sweden                                           30
                                               ...
Austria-Hungary (Ukraine)                         1
Ottoman Empire (Turkey)                           1
Russian Empire (Azerbaijan)                       1
Bosnia (Bosnia and Herzegovina)                   1
French protectorate of Tunisia (now Tunisia)      1
Name: birth_country, Length: 129, dtype: int64
decade
1900    0.017857
1910    0.078947
1920    0.074074
1930    0.254545
1940    0.325000
1950    0.295775
1960    0.280000
1970    0.320388
1980    0.329787
1990    0.415842
2000    0.436975
2010    0.324786
2020    0.391304
dtype: float64
decade  category
2020    Peace         0.5
        Literature    0.5
2010    Peace         0.5
1990    Literature    0.3
2000    Literature    0.3
                     ...
1960    Peace         0.0
1970    Economics     0.0
        Literature    0.0
        Physics       0.0
        Chemistry     0.0
Length: 72, dtype: float64
     year    category                                          full_name  \
19   1903     Physics                        Marie Curie, née Sklodowska
29   1905       Peace  Baroness Bertha Sophie Felicita von Suttner, n...
51   1909  Literature                      Selma Ottilia Lovisa Lagerlöf
62   1911   Chemistry                        Marie Curie, née Sklodowska
128  1926  Literature                                     Grazia Deledda
..    ...         ...                                                ...
982  2022  Literature                                       Annie Ernaux
993  2023     Physics                                    Anne L’Huillier
998  2023       Peace                                   Narges Mohammadi
989  2023    Medicine                                     Katalin Karikó
999  2023   Economics                                     Claudia Goldin

        sex
19   Female
29   Female
51   Female
62   Female
128  Female
..      ...
982  Female
993  Female
998  Female
989  Female
999  Female

[65 rows x 4 columns]